In [ ]:
import numpy as np

def embedding_layer(text, embedding_dim):
  """
  计算一个文本的嵌入向量。

  Args:
    text: 输入文本 (字符串)。
    embedding_dim: 嵌入向量的维度 (例如，300)。

  Returns:
    一个包含文本嵌入向量的 NumPy 数组。
  """
  # 1. 预处理 (简单处理，可以根据需要进行更复杂的预处理)
  words = text.split()  # 简单分割成单词列表
  word_vectors = []
  for word in words:
    word_vectors.append(np.random.rand(300))  # 随机生成一个300维的词向量

  print(f"单词列表: {words}");
  print(f"词向量列表: {word_vectors}");

  # 2. 嵌入向量 ==> 计算文本的嵌入向量 (这里简单地取平均作为示例)
  embeddings = np.dot(word_vectors, np.random.rand(300))  # 使用矩阵乘法计算
  return embeddings


# 示例用法
text = "今天天气真好。"
embedding_dim = 300;
embedding = embedding_layer(text, embedding_dim);

print(f"文本: {text}");
print(f"嵌入向量: {embedding}");
 

# **代码解释:**

# *   `embedding_layer(text, embedding_dim)` 函数接收文本和嵌入维度作为输入。
# *   `words = text.split()`: 将文本分割成单词列表。
# *   `word_vectors = []`:  初始化一个空列表，用于存储每个单词的嵌入向量。
# *   `for word in words:`: 遍历单词列表。
# *   `word_vectors.append(np.random.rand(300))`:  生成一个300维的随机词向量，并添加到 `word_vectors` 列表中。  (这个过程 可以根据需要进行更复杂的词向量生成

单词列表: ['今天天气真好。']
词向量列表: [array([0.69830962, 0.9230806 , 0.62691818, 0.28585026, 0.84799315,
       0.68145127, 0.04134322, 0.38206863, 0.42246576, 0.41992303,
       0.06927439, 0.10380132, 0.93540507, 0.80175072, 0.45536032,
       0.54428323, 0.02957355, 0.33082579, 0.69247017, 0.85148043,
       0.3725039 , 0.48444844, 0.13646667, 0.09612453, 0.18775543,
       0.66521005, 0.04852407, 0.26995412, 0.18173669, 0.71441106,
       0.46632728, 0.29264149, 0.27381429, 0.10916759, 0.29882578,
       0.57522661, 0.10070624, 0.57533163, 0.42617721, 0.40980101,
       0.16157408, 0.86991192, 0.30059711, 0.16353547, 0.9944985 ,
       0.51041676, 0.57737044, 0.13089691, 0.48044777, 0.62290285,
       0.74837147, 0.39038932, 0.4116095 , 0.14716275, 0.80380085,
       0.2564787 , 0.74047359, 0.45944957, 0.00680917, 0.71814462,
       0.87250747, 0.22504879, 0.71975819, 0.12053551, 0.54709771,
       0.96721015, 0.24730024, 0.75843833, 0.72123051, 0.98610741,
       0.9138679 , 0.57863028, 0.407

In [1]:
import torch


print(torch.ones(3, 3));

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [2]:

# 上三角型
print(torch.triu(torch.ones(3, 3), 0));

tensor([[1., 1., 1.],
        [0., 1., 1.],
        [0., 0., 1.]])


In [5]:
tri = torch.triu(torch.ones(3, 3), 0);
print(tri.bool());


print(tri.masked_fill(tri.bool(), -1));

tensor([[ True,  True,  True],
        [False,  True,  True],
        [False, False,  True]])
tensor([[-1., -1., -1.],
        [ 0., -1., -1.],
        [ 0.,  0., -1.]])


# register_buffer 
